### PR TITLE
Xcode 15 compilation error.

### LINKED ISSUE #17: Getting the error Stored properties cannot be marked unavailable with '@available' version 3.1.2 Xcode 15
Stored properties cannot be marked unavailable with '@available'

### PR DESCRIPTION
**Pull request by takasurazeem**
Fixes #17

### CODE REVIEW

**Review by foxbox-hugo — APPROVED** [review]

**Comment by takasurazeem** [comment]
@mohamede1945 could you please make a release for this fix?

**Comment by mohamede1945** [comment]
Done https://github.com/GenericDataSource/GenericDataSource/releases/tag/3.1.3

**Comment by takasurazeem** [comment]
If the quran-ios project points to this version this would fix the compilation error I am having in Xcode 15 and Xcode Cloud.

**Comment by mohamede1945** [comment]
Pull requests are welcome :)

**Comment by takasurazeem** [comment]
Doing.

**Pull request merged**
